[workspace]
members = [
  "crates/app",
  "crates/platform_abi",
  "crates/renderer",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
platform_abi = { path = "crates/platform_abi" }
renderer = { path = "crates/renderer" }
